### ISSUE TITLE
"unknown" is offline after pairing Pixel 9 Pro to a7III

### ISSUE THREAD

**Issue by hoodncsu** [Staacks/alpharemote#5]
ILCE-7M3 v4.01 firmware
Pixel 9 Pro running Android 15 Build AP3A.241105.008

Like #2 the pairing is complete, but shown offline in app. Turning off/on bluetooth on camera brought the connection online, but will then drop after 3-10 seconds. It will then reconnect and drop at the same interval.

App controls work when connection is live.

Happy to provide more info at your request, I'll be trying some other things on my end and will update with any findings.

**Comment by Staacks** [comment]
Currently working on several issues and I am not sure if they are connected or not, so I might have to come back to this one later. However, if you know how to get logs via logcat, this might be a good starting point for me. If you want to try it, I would suggest to use the version linked in #1 as I changed the log tags there, so you can simply filter for all lines containing "alpharemote".

**Comment by Staacks** [comment]
I just published version 0.17 on the Google Play public test branch (might take an hour until your Play Store sees the update). Could you please test it to see if it resolves the issue?

In my opinion it should fix the initial offline state. I am not sure about the connection dropouts afterwards as I have fixed a few things that could cause unreliable connections, but for most users they were permanent dropouts.

**Comment by Staacks** [comment]
"Not ideal, but functional for most use cases" is not what I am trying to achieve :)

Would you be willing to capture some logs and if so, do you know how to do that or should I write some instructions? (I think events tagged with "alpharemote" and "BluetoothGatt" should be enough.)

**Comment by hoodncsu** [comment]
Log is attached
[alpharemote_logcat.txt](https://github.com/user-attachments/files/17750804/alpharemote_logcat.txt)

**Comment by Staacks** [comment]
Not really a big realization yet, but two things that might be worth checking:
1. Not related to the log and a bit of a long shot, but your "Power Save Start Time" on the camera is not set to 10s, is it? (Turning the Bluetooth remote on is supposed to suppress the standby anyway, but I have seen enough bugs in Sonys firmware)
2. This might be a bit more interesting as I am using a Pixel 6 and I would not expect your Pixel 9 Pro to behave that differently. The only big difference I see in your disconnect from mine is that usually, when turning off the camera, the app realizes this immediately and disconnects BEFORE Android reports to the camera that the device disappears. In your logs its the other way around, which is not surprising because Android seems to generate a "device out of range event", telling my app that the device is gone, which then disconnects.
  However, I have always seen two notifications for the device appearing and two matching ones for the device disappearing. By now I have probably searched for days, but never found an explanation or documentation for this and by now I think that this is just a side-effect of the device detection having different event types and generating separate reports for a device communicating and connecting as well as disconnecting and not answering. So, now I am wondering what happens if I just ignore that first device disappeared notification...
  Please try this version here and get a log like before (even if it works for some reason):
  https://cloud.staacks.de/index.php/s/c2fLaGW8dRgmytC
  (Only differences are ignoring that first disappear event, logging new event types as well and enabling autoConnect, which is another feature that might help keeping the connection alive but is not well documented in connection with a companion service.)

One more thing: There is a Bluetooth audio service showing up in the log whenever the camera connects or disconnect. That seems to be an Android thing, because my Pixel 6 is doing the same. However, I was wondering if other Bluetooth devices are connected to the phone at the same time. Might be worth disconnecting them for a test, just to be sure that they do not contribute.

**Comment by hoodncsu** [comment]
That version did the trick, new log is attached. Timeout was set to 1 min, not 10s. I did not have any other bluetooth connections going while this test was being done. Log should include:
1. Initial connection
1. Some pictures taken on initial connection
1. Reconnect after power cycling the camera
1. Reconnect after force quit of app and power cycling camera

[alpharemote_logcat2.txt](https://github.com/user-attachments/files/17759793/alpharemote_logcat2.txt)

Nice work

**Comment by Staacks** [comment]
Oh, I was expecting some insights into the problem, but not a fix yet. But indeed, the log shows that the app can safely ignore the first onDeviceDisappeared and stay connected until it is called a second time when the device is actually turned off.

I'll take that win, although I would love to understand this behavior and opened a [bug report on the Android issue tracker](https://issuetracker.google.com/issues/379170476) hoping that someone there can clarify (or rather open the API to allow me to distinguish the events).

In terms of α-Remote, this fix (or workaround) will be in the next update.
